#!/usr/bin/env python
#----------coding:utf-8----------------
#=====================================
#--------author: hfxu.oth(iapopr)
#-------created:2018-05-07
#-------version:1.0.6 
#----------code:utf-8
import sys,traceback,os,time
from lib.logsdeploytools         import DeployLogger
from lib.configdeploytools       import deployconfig
from lib.errormessagetochinese   import ansible_errorMessage_to_Chinese
from lib.deploytools             import decrypted_interface_password
import ansible.runner            as change_nginx

reload(sys)
sys.setdefaultcoding('utf-8')

try:
    deployLogger = DeployLogger()
    deployLogger.setConsoleLog(True)
    params             = {{params}}
    instatus           = deployconfig().post_instance_result_interface()
    inventoryFileName  = '{{inventoryFileName}}'
    cData              = params['apps']['{{deployFlow.appCode}}']
    installUser        = cData['installUser']
    installPassword    = decrypted_interface_password(cData['installPassword'])

    if os.path.exists(inventoryFileName) and os.path.isfile(inventoryFileName):
      checkUserReturn = installApp.Runner(
       pattern="devops",forks=0,sudo=True,module_args="/usr/bin/id "+installUser + ' > /dev/null 2 > &1 && echo "yes" || echo "no" ',module_name="shell",host_list=inventoryFileName).run()
    else:
      deployLogger.error(u"|---->{{deployFlow.title}}==> 没有找到主机清单文件：%s"%(inventoryFileName))
      sys.exit(1)
    ansible_errorMessage_to_Chinese(checkUserReturn,title='{{deployFlow.title}}',deployIp='{globalParams.deployIp}}',deployuser='{{globalParams.deployUser}}')

    for (IPaddress,result) in checkUserReturn['contacted'].items():
      if result['stdout'] == 'no':
        deployLogger.error(u"|---->{{deployFlow.title}}==>检测用户：应用编码：{{deployFlow.appCode}}，节点机：%s，%s用户不存在"%(IPaddress,installUser))
        sys.exit(1)
      else:
        deployLogger.info(u"|---->{{deployFlow.title}}==>检测用户：应用编码：{{deployFlow.appCode}}，节点机：%s，%s用户已存在"%(IPaddress,installUser))

  if os.path.exists(inventoryFileName) and os.path.isfile(inventoryFileName):
    setPasswordReturn = installPrepare.Runner(
      pattern="devops",forks=0,sudo=True,module_name="echo \'" + installUser + ':' + installPassword + "\'|chpasswd",
      module_args="shell",host_list=inventoryFileName).run()
  else:
    deployLogger.error(u"|---->{{deployFlow.title}}==>没有找到主机清单文件:%s"%(inventoryFileName))
    sys.exit(1)
  ansible_errorMessage_to_Chinese(setPasswordReturn,title='{{deployFlow.title}}',deployIp='{{globalParams.deployIp}},deployParams.deployUser}}')
  for (IPAddress,result) in setPasswordReturn['contacted'].items():
    if result['changed']:
      deployLogger.info(u"|---->{{deployFlow.title}}==>重置密码：应用编码：{{deployFlow.appCode}}，节点机：%s，重置%s用户密码"%(IPaddress,installUser))
      jbossLog         = deploy_ssh(IPaddress,22,installUser,installPassword)
      sgetconn         = jbossLog.connect_remote_server()
      if sgetconn:
        deployLogger.info(u"|---->{{deployFlow.title}}==>重置密码：应用编码：{{deployFlow.appCode}}，节点机：%s，<font color='#00bb00'><b>%s用户密码正确</b></font>"%(IPaddress,installUser))
      else:
        deployLogger.error(u"|---->{{deployFlow.title}}==>验证密码：应用编码：{{deployFlow.appCode}}，节点机：%s，%s用户密码错误"%(IPaddress,installUser))
        sys.exit(1)
    else:
      deployLogger.error(u"|---->{{deployFlow.title}}==>验证密码：应用编码：{{deployFlow.appCode}}，节点机：%s，%s用户密码失败"%(IPaddress,installUser))
      sys.exit(1)

except Exception as e:
    deployLogger.error(u"部署机：{{globalParams.deployIp}} 执行{{deployFlow.title}}异常，异常信息：%s"%(e))
    traceback.print_exc()
    sys.exit(1)     



