#!/usr/bin/env python
#----------coding:utf-8----------------
#=====================================
#--------author: hfxu.oth(iapopr)
#-------created:2018-05-07
#-------version:1.0.6 
#----------code:utf-8
import sys,traceback,os
import ansible.runner            as ansibleCheck
from lib.logsdeploytools         import DeployLogger
from lib.errormessagetochinese   import ansible_errorMessage_to_Chinese

reload(sys)
sys.setdefaultcoding('utf-8')

try:
    deployLogger = DeployLogger()
    deployLogger.setConsoleLog(True)
    inventoryFileName     = '{{inventoryFileName}}'
    currentNode           = '{{currentNode}}' 
  
    if os.path.exists(inventoryFileName) and os.path.isfile(inventoryFileName):
        ansibleReturn = ansibleCheck.Runner(
            pattern="devops",forks=0,sudo=True,module_name="shell",
            module_args="/bin/cat /etc/sudoers|grep -c '{{globalParams.deployUser}}.*NOPASSWD'",
            host_list=inventoryFileName).run()
    else:
        deployLogger.error(u"|---->{{deployFlow.title}}==>没有找到主机清单文件:%s"%(inventoryFileName))
        sys.exit(1)
    ansible_errorMessage_to_Chinese(ansibleReturn,title='{{deployFlow.title}}',deployIp='{{globalParams.deployIp}},deployParams.deployUser}}')
    for (IPAddress,result) in ansibleReturn['contacted'].items():
      if result['changed']:
          if int(result['stdout']) >= 1:     
            deployLogger.info(u"|---->{{deployFlow.title}}==> 检查sudo：节点机：%s 已为{{globalParams.deployUser}}配置sudo权限"%(IPaddress))
          else:
            deployLogger.error(u"|---->{{deployFlow.title}}==> 检查sudo：节点机：%s 没为{{globalParams.deployUser}}配置sudo权限"%(IPaddress))
            sys.exit(1)

except Exception as e:
    deployLogger.error(u"部署机：{{globalParams.deployIp}} 执行{{deployFlow.title}}异常，异常信息：%s"%(e))
    traceback.print_exc()
    sys.exit(1)     
