#!/usr/bin/env python
#----------coding:utf-8----------------
#=====================================
#--------author: hfxu.oth(iapopr)
#-------created:2018-05-07
#-------version:1.0.6 
#----------code:utf-8
import sys,traceback,os
import ansible.runner            as ansibleCheck
from lib.logsdeploytools         import DeployLogger
from lib.errormessagetochinese   import ansible_errorMessage_to_Chinese

reload(sys)
sys.setdefaultcoding('utf-8')

try:
    deployLogger = DeployLogger()
    deployLogger.setConsoleLog(True)
    inventoryFileName     = '{{inventoryFileName}}'
    currentNode           = '{{currentNode}}' 
  
    if os.path.exists(inventoryFileName) and os.path.isfile(inventoryFileName):
        ansibleReturn = ansibleCheck.Runner(
            pattern="devops",forks=0,sudo=True,module_name="ping",
            module_args=" ",
            host_list=inventoryFileName).run()
    else:
        deployLogger.error(u"|---->{{deployFlow.title}}==>没有找到主机清单文件:%s"%(inventoryFileName))
        sys.exit(1)
    ansible_errorMessage_to_Chinese(ansibleReturn,title='{{deployFlow.title}}',deployIp='{{globalParams.deployIp}},deployParams.deployUser}}')
    for (IPAddress,result) in ansibleReturn['contacted'].items():
      if result['ping'] == 'pong':
          deployLogger.info(u"|---->{{deployFlow.title}}==> 检查网络：部署机：{{globalParams.deployIp}}到节点机：%s网络通顺"%(IPaddress))
      else:
          deployLogger.error(u"|---->{{deployFlow.title}}==> 检查网络：部署机：{{globalParams.deployIp}}到节点机：%s网>络异常"%(IPaddress))

except Exception as e:
    deployLogger.error(u"部署机：{{globalParams.deployIp}} 执行{{deployFlow.title}}异常，异常信息：%s"%(e))
    traceback.print_exc()
    sys.exit(1)     
