#!/usr/bin/env python
#----------coding:utf-8----------------
#=====================================
#--------author: hfxu.oth(iapopr)
#-------created:2018-05-07
#-------version:1.0.6 
#----------code:utf-8
import sys,traceback,os
import ansible.runner            as ansibleCheck
from lib.logsdeploytools         import DeployLogger
from lib.errormessagetochinese   import ansible_errorMessage_to_Chinese

reload(sys)
sys.setdefaultcoding('utf-8')

try:
    deployLogger = DeployLogger()
    deployLogger.setConsoleLog(True)
    inventoryFileName     = '{{inventoryFileName}}'
    params                = {{params}}
    checkPort             = params['apps']['{{deployFlow.appCode}}']['params']['port']
    currentNode           = '{{currentNode}}' 
    checkres,einfo        = deploy_nodes_port(currentNode,int(checkPort))

    if checkres:
          deployLogger.warning(u"|---->{{deployFlow.title}}==> 检查端口：节点机：%s 端口%s：被使用"%(currentNode,checkPort))
      else:
          deployLogger.info(u"|---->{{deployFlow.title}}==> 检查端口：节点机：%s 端口%s：没有被占用"%(currentNode,checkPort))

except Exception as e:
    deployLogger.error(u"部署机：{{globalParams.deployIp}} 执行{{deployFlow.title}}异常，异常信息：%s"%(e))
    traceback.print_exc()
    sys.exit(1)     
